workdir: ${hydra:runtime.cwd}  # where the code is executed
primary_nfs: /mnt/research-projects/s/screberg/longterm_images2
local_upload: ${paths.workdir}/temp_data/semifield-upload/
semif_developed: ${paths.workdir}/temp_data/semifield-developed-images/
dev_profiles: ${paths.workdir}/semifield-utils/image_development/dev_profiles/